export interface IProductSliderSchema{
    title: string,
    image:string,
    description?: string,
    price:number,
    weight:string,
    id:number,
    quantity:number,
    offer?:boolean,
    discount?:number,
    outOfStock?:boolean,
    category?:string,
    product_type?:string,
    shelf_life?:string,
    manufacturer_details?:string,
    marketed_by?:string,
    FSSAI_License?:string,
    Customer_Care_Details?:string,
    Expiry_Date?:string,
    Seller?:string,
    Seller_FSSAI?:string,
    Description?:string,
    Disclaimer?:string
}